### ISSUE TITLE
Progress fields become detached windows in Ubuntu 14.04 unity

### ISSUE THREAD

**Issue by gjhiggins** [bitcreditscc/bicreditsnew#10]
“15 weeks behind” and “synchronising with network”

![detached-windows](https://cloud.githubusercontent.com/assets/16417/7004734/d02b0c5a-dc67-11e4-85bb-949d48d2399d.jpg)

**Comment by dragosbdi** [comment]
Same on Windows.

**Comment by bitcreditscc** [comment]
thats how it was meant to be, so you can keep or close them.
