### ISSUE TITLE
Issue with Wallet Crashing

### ISSUE THREAD

**Issue by Goefells** [bitcreditscc/bicreditsnew#21]
Hi 

I'm having an issue with the BCN wallet. It seems to be that the wallet is crashing at a particular block while trying to sync up with the blockchain, however I cannot be sure since the wallet freezes before I can check. Currently it freezes about 9 days from the current block.

This is a screenshot of what I encounter- https://www.dropbox.com/s/so4q7m1whtk9ini/Screenshot%202015-04-19%2014.10.08.png?dl=0

I am running the latest wallet. 

Thank you.

**Comment by bitcreditscc** [comment]
should be fixed now
