### ISSUE TITLE
Stats refresh button dumps core

### ISSUE THREAD

**Issue by gjhiggins** [bitcreditscc/bicreditsnew#38]
“Floating point exception (core dumped)”

Ubuntu 14.04

**Comment by bitcreditscc** [comment]
Which branch?

**Comment by gjhiggins** [comment]
master

**Comment by gjhiggins** [comment]
buried in it atm, else I'd have a go a nailing it down more precisely

**Comment by bitcreditscc** [comment]
strange, we haven't merged anything to master in over two weeks, ok i'll tag this, meanwhile i'd suggest you work off the dev branch.

**Comment by thelonecrouton** [comment]
I had the same issue with the bidbased branch until, bizarrely, I removed --enable-debug from my ./configure line. The current rc branch compiled fine on my test box (without the debug switch) but still gave me the floating point error on my laptop until I removed it there also.

**Comment by gjhiggins** [comment]
I'm unable to reproduce the fault when running under Qt creator's debug facility. I was going to suggest that the fault might lie in a debug print statement but clearly it doesn’t.

**Comment by bitcreditscc** [comment]
How are you using QT creator? I just tried building using it and it's failing with :- /home/devsys1/bitcredit/src/utiltime.cpp:57: error: #error missing boost sleep implementation

**Comment by dragosbdi** [comment]
Same error on Win
![error](https://cloud.githubusercontent.com/assets/11424164/9423837/e569f184-48dd-11e5-85cf-cf6bb947c9a4.jpg)

**Comment by bitcreditscc** [comment]
Hmm, will try to work out what it is but it's likely because i forgot to handel situations where there are no bids for coins. I'll send some coins to the addresses when i get to my wallets and try to think how to structure the try statement, but again Qt is finicky about handling exceptions. I'll let you know what i come up with.

**Comment by bitcreditscc** [comment]
Try it now, just open any wallet, no need to recompile.

**Comment by dragosbdi** [comment]
It works at me now ...

**Comment by bitcreditscc** [comment]
resolved
