### ISSUE TITLE
"banknode start" gives "sync in process. Must wait until client is synced to start"

### ISSUE THREAD

**Issue by thelonecrouton** [bitcreditscc/bicreditsnew#47]
Client reports itself synced, agrees with chainz, system and client time match.

**Comment by bitcreditscc** [comment]
thers been a couple of updates,do you still have the issue?

**Comment by thelonecrouton** [comment]
No, all working fine as of my build this morning. :)

**Comment by bitcreditscc** [comment]
Great :)
