### ISSUE TITLE
Microsoft C++ Runtime Error - Wallet Crashes - Windows 7 Pro (64bit)

### ISSUE THREAD

**Issue by Baudrate1** [bitcreditscc/bicreditsnew#8]
Wallet version --- Windows x64 0.30.16b

Details of message received by Microsoft Windows Error Reporting.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	bitcredit-qt.exe
  Application Version:	0.3.15.0
  Application Timestamp:	00290158
  Fault Module Name:	bitcredit-qt.exe
  Fault Module Version:	0.3.15.0
  Fault Module Timestamp:	00290158
  Exception Code:	40000015
  Exception Offset:	000000000104868a
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	9d3c
  Additional Information 2:	9d3c08f47bb059d112ff199900026d8c
  Additional Information 3:	f3c9
  Additional Information 4:	f3c9d4a92460aba6e3162f83e1866ee6

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Debug Log info

GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: cHRM chunk does not match sRGB
GUI: QSystemTrayIcon::setVisible: No Icon set
2015-04-05 12:26:32 GUI: "registerShutdownBlockReason: Successfully registered: Bitcredit Core didn't yet exit safely..."
2015-04-05 12:26:32

**Comment by bitcreditscc** [comment]
These are warnings, can you search and post for the error part

thanks

**Comment by bitcreditscc** [comment]
should be fixed now
